# Compañías Administradoras

winter-solstice-description = Las tres ramas de la Federación de Marines Trans-Solares están bajo la dirección del mando supremo unificado de la Federación, conocido como Winter Solstice.


# Compañías Núcleo

drake-industries-description = Eficiencia, beneficios, fiabilidad. Drake Industries es una antigua gran empresa comercial que se convirtió en el mayor gigante industrial del sector. Desde elegantes diseños de naves civiles hasta el refinado de materiales, se mantiene a flote principalmente alimentando los conflictos circundantes. Oficialmente, desaconseja cualquier tipo de hostilidades cometidas por los miembros de la empresa. Promete beneficios fáciles a todos los pilotos, ingenieros y guardias de seguridad privada capaces que estén dispuestos a alistarse bajo su bandera. Eso sí, no te sorprendas cuando las condiciones laborales consistan en plazos de entrega agotadores, sin descansos para ir al baño y durmiendo en un catre sucio.

steel-hammer-description = Masivo conglomerado industrial y Empresa Núcleo. Se especializa en el diseño, construcción y equipamiento de cascos de naves estelares empleados por civiles, CPM o el mejor postor, utilizando startups de base, aliados comerciales industriales establecidos e ingenieros de sistemas independientes subcontratados. Principal proveedor de cascos y naves equipadas para el sector Colossus, lo que lo convierte en una de las espadas del conflicto que se avecina entre las principales facciones que compiten por la dominancia. Tras el histórico colapso de la megacorporación Nanotrasen y los Aliados del Syndicate, las subsidiarias de fabricación de cascos motivadas por el beneficio que sobrevivieron de ambos bandos se dieron cuenta de que la mejor medida era separarse lo más posible de las potencias destruidas y empezar de nuevo. SHM acepta planos de todo tipo de diseñadores independientes (o no) por todo tipo de razones, desde mejorar el catálogo de cascos universalmente disponibles en el mercado intergaláctico hasta… contratos faccionarios extremadamente valiosos. **Los miembros de Steel Hammer Manufacturing suelen ser constructores, desguazadores, diseñadores o mantenedores de naves.**

harmony-medical-enterprises-description = Harmony Medical Enterprises es una corporación dedicada exclusivamente a la atención médica y los suministros. ¿Te han herido en el campo de batalla? HME es quien proporcionó a tus superiores un trato con descuento en bolígrafos de combate y varios medicamentos que te mantienen en la lucha por más tiempo. Harmony Medical Enterprises es el principal fabricante que introduce en el sector cosas como botiquines, bolígrafos de combate, estuches de medipen, equipamiento médico y toda la tecnología para salvar vidas. Aunque no tienen dominio sobre la clonación, tienen lo mejor después de eso: medicina para los vivos.

midnight-arms-co-description = Midnight Arms Company aprovechó una galaxia recién reconstituida, una que carecía de megacorporaciones y las prohibía en todos sus aspectos. Midnight Arms proporciona armamento a masas independientes y diversas corporaciones para cualquier necesidad que tengan; el uso que se les dé depende de quienes los compran. Las armas son necesarias para todo en esta era: autodefensa, expediciones, caza de recompensas. Todos son trabajos que necesitan armas para llevarse a cabo, y MACo simplemente se encuentra siendo el principal proveedor.

ussp-description = Los Remanentes de la USSP son los elementos supervivientes de la 78ª Flota Expedicionaria y su 13er Batallón de Infantería Naval adjunto. Encargados en su día de asegurar el Sector Colossus bajo la Operación Mesa Redonda, la flota expedicionaria fue destruida por una repentina y desorganizada orden de retirada, perdiéndose gran parte de ella durante la retirada a través de las lejanas franjas del sector. Aislados de su lejano hogar y sin más órdenes del Mando Naval de la USSP, los supervivientes ahora resisten en el aislamiento. La Infantería Naval, agobiada por bajas sostenidas y un liderazgo endeble, sigue siendo una fuerza curtida en batalla pero cada vez más al límite. Mantenidos unidos por la camaradería, el orgullo y la obstinada creencia de que su sacrificio aún debe tener sentido, los Remanentes luchan ahora por preservar lo que queda, algunos aferrados a la esperanza de que algún día la Unión regresará, mientras otros empiezan a dudar de que lo haga alguna vez.

# Compañías Principales

dark-matter-enterprises-description = De las cenizas de la Última Guerra Corporativa surgió Dark Matter Enterprises (DME), un faro de ambición pragmática en una galaxia que aún se tambalea por el devastado panorama interestelar creado por la codicia corporativa y las diferencias ideológicas. Mientras la TSF y la USSP luchaban por la dominancia galáctica, un colectivo de visionarios contratistas corporativos vio el vacío de poder dejado por la ausencia de las viejas potencias que solían existir. Estos individuos forjaron la DME con un único propósito: trascender los viejos métodos controlando y potenciando el flujo de conocimiento y recursos. Posicionándose como indispensables para todos, pero sin deber nada a nadie. Su estructura centralizada es una respuesta directa a la fragmentación caótica de sus predecesores, garantizando una toma de decisiones ágil y una visión estratégica unificada.

aetherion-dynamics-description = Representando la vanguardia de la innovación tecnológica, Aetherion Dynamics es reconocida por su invención del sistema de Lanzamiento y Proyectil de Gas Comprimido (CGLP) utilizado en la batería de turboláser ADEX-9 Dymere, así como por armas innovadoras adicionales sin una filosofía de diseño coherente. Entre todas sus famosas armas de nave, iniciaron la Revolución de Artillería en el período previo al conflicto en el Sector Colossus. Tienen reputación de fabricantes y diseñadores de alta calidad, más interesados en construir un producto eficaz que en obtener beneficios.

horizon-energy-description = Líderes en extracción de gas, desde el valioso Plasma Prismático del monolito hasta los asteroides llenos de gas del borde exterior del sector Colossus. Son los líderes actuales de la industria en el campo de la extracción y la ingeniería atmosférica. Ofrecen servicios útiles tanto para los mineros novatos y emprendedores como para los gaseadores veteranos y experimentados. Lo más probable es que el aire que respira el espacial corriente y el rastro de gas que deja su nave provengan de Horizon Energy.


# Compañías Menores

universal-states-of-america-description = Los Estados Universales de América son un grupo de mercenarios fanáticos que desean llevar los valores de los antiguos Estados Unidos al siglo XXV. Funcionan prácticamente como un grupo CPM, subcontratando milicianos patrióticos como mercenarios bajo el nombre de 'Vanguards' para financiar sus sueños de crear una nación vasta y poderosa similar a los EE.UU., un sueño que lo más probable es que nunca cumplan. Pero, a sus ojos, la lógica y el sentido común no pueden con la libertad. Ejerce tu derecho a la Segunda Enmienda, grita a un cocinero porque llama 'Patatas Espaciales' a sus patatas fritas en lugar de 'Patatas de la Libertad', y deja claro que eres un maldito patriota de los Universal que ama las armas, defiende a los débiles, come hamburguesas y conduce camiones espaciales.

civil-defense-milita-description = Una empresa relativamente nueva fundada dentro del Sector Colossus, la Milicia de Defensa Civil fue formada para proteger a la población civil y sus intereses. Respondiendo ante individuos de alto rango elegidos por su reputación, la milicia participa en actos de altruismo como defender puntos de interés importantes y mantener altos al fuego para que los civiles puedan comerciar con seguridad dentro del sistema. La C.D.M. está compuesta por contratistas y mercenarios voluntarios y solo tiene acceso al equipamiento disponible para ellos. Por el pueblo. Defiende y no participes en actos de violencia sin sentido. Eres el defensor de quienes no pueden defenderse a sí mismos.

southern-peak-mercenaries-description = "Un buen renegado es un renegado muerto." dice el lema de esta despiadada compañía de mercenarios. Los Southern Peaks se formaron a lo largo de la frontera espacial TSF-Renegado en represalia contra los piratas e insurgentes que invadían el territorio, combinado con una absoluta desconfianza en la TSFMC. Sin necesidad de ninguna otra organización, TSP tiene como objetivo combatir al Sector Renegado por su cuenta.

ullman-industries-description = La primera vez no es un crimen de guerra. Originalmente una empresa básica en el sector sin ley para la producción de armas ligeras y productos farmacéuticos, una vez que llegó la TSF, la mayoría de las empresas pasaron al sector público, registrándose y cumpliendo "prácticas laborales seguras" y pagando a los empleados un "salario digno", además de perseguir a los líderes empresariales por cargos de "crímenes de guerra". Ullman Industries rompió esta tendencia manteniéndose fiel a sus raíces como elemento marginal, suministrando armas, armaduras, naves y lo que sea a todos y cada uno de los clientes de la Dinastía Phaetheon. En resumen: si es ilegal en el espacio de la Federación, probablemente lo vende Ullman Industries. Es más, probablemente ellos mismos lo fabricaron.

nosske-eien-rnd-description = Renombrada en otros sectores por su tecnología y avances de vanguardia, Nosske-Eien había comenzado a expandirse y adentrarse en el sector Renegado contratando mano de obra local, ya sean civiles corrientes, pilotos o mercenarios, para la investigación sobre la xenoarqueología, xenobiología y avances tecnológicos locales. Nosske-Eien ha sido la fuente principal de los recientes avances y equipamientos tecnológicos científicos, así como de equipos de minería de asteroides de alta tecnología y, próximamente, transbordadores. Aunque hay rumores de que sus contratistas desaparecen aleatoriamente de vez en cuando. Esperemos que sea solo una treta y no haya nada de qué preocuparse, ¿verdad?

blackhawkpmc-description = El grupo Blackhawk Military Contracting (BMC) es un grupo de mercenarios premium que opera en el sector Colossus. Se espera que los mercenarios del grupo estén entrenados y sean profesionales. Realizan tareas mercenarias que van desde la protección de activos hasta el asesinato, mientras mantienen su reputación. El grupo es bastante nuevo, creado por un grupo de mercenarios independientes que buscan construir un poderoso grupo mercenario. En este momento, las operaciones de reclutamiento están en alza. Blackhawk PMC ofrece una amplia gama de servicios, desde seguridad privada hasta asesinatos a pleno rendimiento. Los mercenarios de Blackhawk visten de verde y a menudo evitan llamar la atención. Lucha contra cualquiera por cualquier cosa para ganar dinero.

# Grupos Religiosos

zealots-of-balaam-description = Los Zelotes y peregrinos de Balaam son luditas con una extrema aversión al uso de la alta tecnología y los seres de alta tecnología. Como seguidor de Balaam, trabaja bajo las órdenes de un zelote mayor o un Obispo para ayudarlos a recaudar sus diezmos y realizar inspecciones en busca de máquinas pensantes heréticas. Nunca escuches la blasfemia de las otras compañías. Destruye o elimina toda la tecnología de escudos que encuentres, y toma cualquier FTL utilizado por los infieles. Asegúrate de elegir bien tus objetivos para estas acciones, pues a menudo estarás en minoría. Saber esto: Balaam ama nuestras formas orgánicas; matar masivamente a posibles conversos no ayuda en nada a los Obispos. Mantén al mínimo el número de orgánicos muertos. Pero si se niegan y continúan albergando máquinas heréticas, métodos de persuasión más contundentes podrían resultar útiles para los planes de Balaam.

cult-of-the-machine-god-description = La carne es débil. Caminar por el sendero del Culto al Dios Máquina es rechazar el caos de la carne y abrazar el orden divino de la lógica. Los fieles actúan con precisión y propósito, nunca guiados por la emoción o el impulso. El avance no viene a través de la pasión, sino mediante la mejora calculada y la disciplina inquebrantable. Quienes mandan en el Culto lo hacen mediante una claridad algorítmica, desplegando operativos Ascendidos con eficiencia mecánica y extendiendo su influencia a través de Devotos ocultos o Vasijas errantes lideradas por Tecnosacerdotes. Sea aplicando la doctrina en sectores lejanos o ejecutando una dominación fría y estratégica, cada acción debe servir a la gran ecuación. En todas las cosas, la razón debe gobernar, y a través de ella, la voluntad del Dios Máquina se hace manifiesta...

The-Hive-description = ¿Para qué perfeccionar lo viejo cuando puedes convertirte en algo nuevo? The Hive son cultistas que dedican su cuerpo al camino de la supremacía evolutiva y a las órdenes de la Madre Reina. Este es el lugar para quienes creen en el progreso a través de la transformación, sin importar lo monstruoso que sea. La pureza genética es pecado; siempre busca convertirte en una versión mejorada de ti mismo. Recuerda que tu fe reside en la voz guía de la Madre Reina; seguir a otro es abandonar the hive. La supervivencia del más apto: si la Bestia fue lo suficientemente débil como para morir a tus manos, puedes cosechar sus órganos a tu antojo.

# Compañías del Mercado Negro

paycheck-bratva-description = Los Paycheck Bratva son una red de crimen organizado originaria del territorio de la USSP, que se ha infiltrado en el sector Colossus desde que la superpotencia espacial se trasladó allí. Se especializan principalmente en el tráfico de drogas de alto perfil, el contrabando y los robos de gran impacto, además de atentados contra objetivos con diversos precios asignados. Junto a esto, operan bajo un código simplista: siempre disparar a matar si se abren fuegos, nunca consumir drogas y mucho menos las propias, y matar a quienes hayan derramado sangre de Paycheck Bratva. En general, una fuerza intimidante, vestida con chalecos de kevlar, trajes y corbatas y pasamontañas o máscaras similares; una facción tanto para matones como para ladrones profesionales.

viper-group-description = Anteriormente una compañía de corso del Syndicate que operaba bajo el ala de Gorlex con una rígida doctrina militar, cuya única misión designada era interrumpir las rutas de envío interestelares a lo largo de las franjas del territorio NT. Después de que la Unión de Planetas Soviéticos Socialistas declarara su independencia de la Confederación, el Viper Group vio una oportunidad de explotar la situación de la nación tras la devastadora guerra corporativa y formó una oficina subsidiaria en el espacio de la USSP para facilitar operaciones locales contra la TSF bajo el pretexto de "ayudar" en la estabilización de las fronteras de la USSP contra sus antiguos amos, ganando una respetable reputación entre las primeras filas de la USSP y obteniendo beneficios vendiendo equipamiento antiguo saqueado de NT y el Syndicate al gobierno de la USSP y a los mercados negros locales. Tras la guerra corporativa, los Vipers habían migrado completamente al espacio de la USSP con un frente de CPM, alejándose de la asociación pública con el ejército de la USSP y actuando de forma independiente. Con la USSP cada vez más satisfecha con su esfera de influencia entre las estrellas tras una serie de devastadoras incursiones de la TSF que reclamaban territorio a la USSP, los Vipers abandonaron su dominio para acechar con su mejor virtud: la Codicia. Los Vipers expandieron su alcance hacia zonas más oportunistas donde nadie los miraría dos veces al ver su insignia, como planetas fronterizos desestabilizados y centros espaciales de varios grupos de interés, volviéndose notorios por llevar a cabo ataques a rutas de suministro y envío; especialmente las de la emergente TSF y PD. Con el liderazgo cambiando de manos violentamente con frecuencia una vez que los colmillos de un comandante Viper se vuelven romos, los Vipers son vistos como un comodín cuyo único interés son los créditos y cumplir los contratos al pie de la letra. Las favorables relaciones con el mercado negro de Colossus aceleraron su llegada al sector. Para quienes anhelan el peligro y la riqueza, los Vipers no se inclinan ante nadie; lealtad entrelazada por la hermandad y colmillos descubiertos por créditos.

cerberus-surplus-provisions = Cerberus Surplus Provisions, o CSP, es un conglomerado de corredores, productores y especialistas que operan en diferentes divisiones y que recientemente fueron impulsados por la Dinastía Phaetheon, a quien la CSP apoya abiertamente en la invasión de Colossus. Sus miembros trabajan juntos para obtener beneficios mutuos y apuntalar la Dinastía. Su MO es evitar conflictos, vender lo que puedan conseguir y asegurarse de que los 'intereses comerciales' estén representados en el sector. Cualquier cosa puede comprarse y venderse en el sector Colossus, solo necesitas la astucia para lograrlo.

redsail-corsairs-description = Los RedSail Corsairs, o RSC, son un peligroso e influyente grupo de piratas y malhechores, conocidos públicamente por llevar a cabo actividades ilegales y violentas contra civiles, funcionarios y personal militar por igual. Su fuente de ingresos y especialización es el secuestro, el robo de carga, la toma de rehenes y el robo a mano armada. Están marcados abiertamente por el Colossus Central como organización criminal. En conjunto, los Corsairs funcionan como una unión entre saqueadores libres de todo tipo que han jurado lealtad entre sí.

plxcor-description = PLXCOR es una destacada organización terrorista que opera en el sector Colossus. Los miembros de PLXCOR, también conocidos como unidades PLEX, son conocidos por sus opiniones extremas sobre la vida orgánica y por su propensión a la violencia. Todas las organizaciones que operan en el sector Colossus la clasifican como organización terrorista y la buscan por delitos que incluyen: asesinatos en masa; secuestros en masa; terrorismo generalizado; bioterrorismo; bioterrorismo con letoferol; tortura; mutilación corporal; tráfico de formas de vida sintientes; ciborgización forzada de formas de vida sintientes; etc. Deben considerarse armados y extremadamente peligrosos.
